function bla(bli : number, blo : number) : number { return bli+blo; }
const blA_3 = 3 : number;
const pi = 3.14 : number;
/* After we declared constants and functions *test
 * we can now begin our start function =)
 */
function start () : void {
//this is also a comment...
var io = 32 + 2 * blA_3 : number;
var blo_KAI_bli : number;
blo_KAI_bli = bla(io,pi);
var lastOne = bla(blo_KAI_bli,45) : number;
}
